triggers:
  flow-listener-1:
    name: Flow Listener
    parameters:
      id: getwatchlistquote
    enabled: true
    invoke:
      flow: NewFlow
      parameters:
        request: $.request
        config: $.config
        env: $.env
